version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restopass
    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: restaurant-redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
      image: adminer
      restart: always
      ports:
      - "8081:8080"

volumes:
  mysql-data:
