version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restopass
    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
